### ISSUE TITLE
App crashes when double clicking on icon in grid ..

### ISSUE THREAD

**Issue by MacSass** [ctreadw6/InfinittonWPF#19]
Hi ctreadw6,
starting to input my issues that I fould and feature reqeuest ...

When I double click on an icon that I have dragged onto the grid the app crashes. I know I should only single click to configure - but I keep double clicking :-)

Low priority bug, I would say ..

Regards - MacSass

**Comment by ctreadw6** [comment]
Double click is meant to actually execute that action. It should execute the EXE, change to the folder, etc.
I am not seeing the any crashes/exceptions when I double click on them. I will look into this some more.

**Comment by MacSass** [comment]
Ah, I see - I guess the crash is caused by the fact that I did not have a valid path configured, as I did not see the dialogue working and did not think of manually pasting a path.
For dummies :-) it might makes sense to check the path is valid before executing it - but that is low priority, I guess ...
Thanks MacSass

**Comment by ctreadw6** [comment]
Not having a valid path should be fine with the current code. I don't think checking that a path exists is the right way to go. I just tell the operating system to execute whatever is in that box. All of these are valid and would be hard to check for: "www.google.com", "chrome.exe", "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe".

I think I found the issue. It was related to not having detected a device. Should be fixed now.
