### ISSUE TITLE
No indication if Infinniton found - no action seen on infinniton

### ISSUE THREAD

**Issue by MacSass** [ctreadw6/InfinittonWPF#21]
This obviously is a big issue for me:
There does not seem to be any indication in the app if the infinitton board was found or not ... there should be some status line or similar ...

Also - whatever I do - I do not see any reaction on my infinniton board. Does this need some special driver to be installed? Infinniton SW is working fine and I´m fully closing down infinniton SW before using your editor.

Regards - MacSass

**Comment by MacSass** [comment]
Hi ctreadw6,
thanks for your response - I have installed teh VC++ runtime from redist folder.
I could not install the .net 4.6.2 is though, as windows states that I already have a newer version installed (I think .net 4.7.1 comes with Windows 10 version 1803).

I can´t get InfinittonWPF to do anything with my Infinitton though. I checked PID and it is identical with 0x1f40.

Could you add a flag in the app to state "Infinitton found" or something?

Right now I´m a little bit lost what could be the cause ... Infitton SW itself works fine with my Infinitton.

Regards - MacSass

**Comment by MacSass** [comment]
Hi again,
looks like it has todo with the .net releases targeted for the components. I ran it in Visual Studio 2017 and was seing an exception:
"System.DllNotFoundException" in USBInterface.dll

My windows has .net 4.7.2 that came with Windows 10 April 2018 update - thus I can´t install 4.6.2.

Also there might be a conflict with the processor platform x86 / x64 - is it build for both? (Obviously have a x64 processor). When I compile for "Any CPU" I do see a warning that the processor architecture of the referenced USBInterface.dll (x86) would not match the build project (MSIL).
Is there a USBInterface.dll for x64?
Not really sure what that all means - but hope that might help you to find why my infinitton is not seen ...

Regards - MacSass

Hope that helps -

**Comment by ctreadw6** [comment]
Thanks for looking into that more. That specific error makes me think there is something wrong with the hidapi.dll or the reference to it. This is the C++ dll I mentioned before. 

The USBInterface.dll is a C# wrapper around the hidapi.dll. It could possibly be an issue with the build architecture like you mentioned. There could also be another dll that it depends on that I am unaware of. I will look into it in a few hours when I get home.

**Comment by MacSass** [comment]
Hi @ctreadw6,

ok - I see - unfortunately I do not have much experience with C++ nor DLL programming - but obviously there must be somthing going wrong inside USBInterface.dll code.
I have no clue how I could see the complete exception - as much as I could google debugging is not working across the "bounderies" so all I see is the 
"System.DllNotFoundException" in USBInterface.dll

So - I have Visual Studio 2017 installed, project builds with no error - but a warning comes up from the compiler that USBInterface.dll would be x86 architecture, which would not match project "MSIL" (what ever that should be) and might cause issues during runtime ...

If there is anything I can help with feel free to let me know, either here or by mail.

Thanks for your work on this - MacSass

**Comment by ctreadw6** [comment]
I added a build of a a tester application for the c++ hidapi library. Its Test/hidtest.exe
This program lists your devices and tries to connect to the infinitton device and change its brightness a few times. If this works, then we know you can run the hid library and have the correct c++ runtime stuff.

I also changed the hidapi to its release version. I had the debug version. It is build in x86.
I changed all of the C# stuff to x86 from Any CPU. This may or may not be what we want to settle on, but it will give you a chance to test the software with everything being built for x86.

**Comment by MacSass** [comment]
Hi, unfortunately there is no change - still shows "device disconnected" - I´m running the version from folder Infinitton WPF/bin/Release, right?
I already had played with the targeted .net versions in Visual Studio but also without success. I´ll fire up Visual Studio later to see if this shows anything more helpful ...

![grafik](https://user-images.githubusercontent.com/25532047/44464983-86766000-a61c-11e8-8a16-56c514b9258f.png)

Regards - MacSass
