### ISSUE TITLE
Feature request: Buttons depending on window (application) that has focus

### ISSUE THREAD

**Issue by MacSass** [ctreadw6/InfinittonWPF#23]
One of my most desired features I´m missing in Infinniton SW is the ability to have the icons change automatically when a certain application get´s focus ... that should be dynamic.

E.g. if Photoshop comes to focus the icons change to a Photoshop set - if switching to Lightroom, the respective set becomes activated ...

This might require a different way to configure and safe configuration sets than what we see in Infinniton SW right now.
Infinniton SW offers this type of functionality when an application is launched, but they do not recognize when the focus changes ...

I think this feature request is for the future - but should be considered from a UI point of view already, so it can be added more easily later.

Regards - MacSass

**Comment by ctreadw6** [comment]
Definitely like this idea and is very doable. Thanks for all the feedback!

**Comment by ctreadw6** [comment]
Added this in. Great idea!
