### ISSUE TITLE
Settings not retained

### ISSUE THREAD

**Issue by MacSass** [ctreadw6/InfinittonWPF#24]
Hi again,
when I close IWPF and restart, all configuration I have made is lost ... should it come up with the old settings automatically? Where does it save settings?

Regards - MacSass

**Comment by ctreadw6** [comment]
It should. It saves them to the settings file associated with the exe. Should be in a file called InfinittonWPF.exe.config located in (I think) %appdata%/InfinittonWPF or %localappdata%/InfinittonWPF

I will double check the code this evening, but this not saving probably also has to so with your device not being detected.

**Comment by MacSass** [comment]
Hi,
ok, I do see this file in C:\Users\Username\AppData\Local\InfinittonWPF\app-1.0.0 but it does not seem to have any button config in it - just brightness and AFKDimTimeInSeconds ... maybe that is because it can´t talk to my infinitton yet. Let´s just tackle the basic issue first - then we can look into this ...

**Comment by MacSass** [comment]
Ok, I can confirm this is working - I think it was caused by my device not being recognized - thus the settings were not saved. Eventually saving can be made independent of this?
Otherwise I think this issue can be closed.
