### ISSUE TITLE
No way to remove a button

### ISSUE THREAD

**Issue by MacSass** [ctreadw6/InfinittonWPF#25]
Hi @ctreadw6 ,
I currently miss a way to remove a configured button from the configuration.
I was thinking the "discard" button would do this - but it does not. I would propose to relabel that button to the more common "cancel" (if this is what it is supposed to do).

For removal of a configured button I would propose to either add a right mouse menu to the button wich has an entry for "remove button" or add an additional button to the button configuration that is labled "delete".

Ideal for usability and ease of use would be to have both ...

**Comment by ctreadw6** [comment]
I like the idea to add a button for this. Currently I think the delete key should do the trick. 
The discard button resets any changes you have made to the config stuff for a button.
