### ISSUE TITLE
Enhancement request: Safe/Load configurations

### ISSUE THREAD

**Issue by MacSass** [ctreadw6/InfinittonWPF#26]
Hi,
it might make sense to have an option to individually safe and load a configurtion set.
So you could move configurations between PCs easily and also have "test" configurations, etc.

I know knowledgable people could do that by copying the settings file, etc., but from usability that is not ideal. I would propose to have an export and an import button on the lower left hand side.

**Comment by ctreadw6** [comment]
Added this in. It's in the menu on the out if you would like to try it.
