### ISSUE TITLE
Enhancement request: Font size and remove icon

### ISSUE THREAD

**Issue by MacSass** [ctreadw6/InfinittonWPF#37]
Hi,
I like the "Title" option for some button, just the font is very small right now (I know - there is not a lot of space).
Also the text is always "overlayed" on the basic icon (I would have to create a black image to get rid of it).

I think it would make sense to allow users to select the font (size / color at least) and an option to set a full color background instead of using an image.

What do you think?

**Comment by ctreadw6** [comment]
Good idea - I wanted to add a more intuitive way to add an icon, this will make another good addition to that.
